name: location
description: A Flutter plugin to easily handle realtime location in iOS and Android. Provides settings for optimizing performance or battery.
version: 4.4.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^2.3.0
  location_web: ^3.1.1
dev_dependencies:
  async: ^2.5.0
  build_runner: ^1.11.5
  flutter_test:
    sdk: flutter
  test: ^1.16.5
